"""Python enum code generator for discovered observation types."""

from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from myheartcounts_ds.typegen.categories import SUPPORTED_CATEGORIES
from myheartcounts_ds.typegen.discovery import DiscoveredType


def generate_enum_code(
    discovered_types: list[DiscoveredType],
    project_id: str | None = None,
) -> str:
    """Generate Python enum source code from discovered types.

    Args:
        discovered_types: List of DiscoveredType objects to include in the enum.
        project_id: Optional project ID to include in the header comment.

    Returns:
        Python source code as a string containing the DiscoveredObservationType enum.
    """
    # Group types by category
    types_by_category: dict[str, list[DiscoveredType]] = defaultdict(list)
    for dt in discovered_types:
        types_by_category[dt.category].append(dt)

    # Build the enum members
    lines: list[str] = []

    # Header
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines.append('"""Auto-generated HealthObservation types enum.')
    lines.append("")
    lines.append("DO NOT EDIT MANUALLY - regenerate with `mhc-ds generate-types`.")
    lines.append("")
    lines.append(f"Generated: {timestamp}")
    if project_id:
        lines.append(f"Source: {project_id}")
    lines.append(f"Total types: {len(discovered_types)}")
    lines.append('"""')
    lines.append("")
    lines.append("from enum import Enum")
    lines.append("")
    lines.append("")
    lines.append("class DiscoveredObservationType(Enum):")
    lines.append('    """Observation types discovered from the database.')
    lines.append("")
    lines.append("    This enum is auto-generated by scanning the Firestore database")
    lines.append("    for HealthObservation subcollections. Each member's value is the")
    lines.append("    raw identifier string as stored in the database.")
    lines.append("")
    lines.append("    Example:")
    lines.append("        >>> obs_type = DiscoveredObservationType.HK_QUANTITY_STEP_COUNT")
    lines.append('        >>> print(obs_type.value)  # "HKQuantityTypeIdentifierStepCount"')
    lines.append('    """')
    lines.append("")

    # Generate members grouped by category
    category_order = {cat.name: cat for cat in SUPPORTED_CATEGORIES}

    for category in SUPPORTED_CATEGORIES:
        if category.name in types_by_category:
            types_in_category = types_by_category[category.name]
            # Sort alphabetically within category
            types_in_category.sort(key=lambda d: d.enum_name)

            lines.append(f"    # {category.description}")
            for dt in types_in_category:
                lines.append(f'    {dt.enum_name} = "{dt.raw_identifier}"')
            lines.append("")

    # Add lookup function
    lines.append("")
    lines.append("def get_observation_type_by_identifier(")
    lines.append("    identifier: str,")
    lines.append(") -> DiscoveredObservationType | None:")
    lines.append('    """Look up an observation type by its raw identifier.')
    lines.append("")
    lines.append("    Args:")
    lines.append("        identifier: The raw identifier string")
    lines.append('            (e.g., "HKQuantityTypeIdentifierStepCount").')
    lines.append("")
    lines.append("    Returns:")
    lines.append("        The matching DiscoveredObservationType, or None if not found.")
    lines.append('    """')
    lines.append("    for member in DiscoveredObservationType:")
    lines.append("        if member.value == identifier:")
    lines.append("            return member")
    lines.append("    return None")
    lines.append("")

    return "\n".join(lines)


def write_enum_file(
    discovered_types: list[DiscoveredType],
    output_path: Path | str,
    project_id: str | None = None,
) -> Path:
    """Generate and write the enum file.

    Args:
        discovered_types: List of DiscoveredType objects to include.
        output_path: Path to write the generated file to.
        project_id: Optional project ID to include in the header.

    Returns:
        The Path where the file was written.
    """
    output_path = Path(output_path)
    code = generate_enum_code(discovered_types, project_id)
    output_path.write_text(code)
    return output_path


def get_default_output_path() -> Path:
    """Get the default output path for generated types.

    Returns:
        Path to the generated_types.py file in the typegen package.
    """
    return Path(__file__).parent / "generated_types.py"
