"""Auto-generated HealthObservation types enum.

DO NOT EDIT MANUALLY - regenerate with `mhc-ds generate-types`.

Generated: 2026-01-21 09:45:28 UTC
Source: som-rit-phi-mhc-prod
Total types: 55
"""

from enum import Enum


class DiscoveredObservationType(Enum):
    """Observation types discovered from the database.

    This enum is auto-generated by scanning the Firestore database
    for HealthObservation subcollections. Each member's value is the
    raw identifier string as stored in the database.

    Example:
        >>> obs_type = DiscoveredObservationType.HK_QUANTITY_STEP_COUNT
        >>> print(obs_type.value)  # "HKQuantityTypeIdentifierStepCount"
    """

    # HealthKit quantity types (e.g., step count, heart rate)
    HK_QUANTITY_ACTIVE_ENERGY_BURNED = "HKQuantityTypeIdentifierActiveEnergyBurned"
    HK_QUANTITY_APPLE_EXERCISE_TIME = "HKQuantityTypeIdentifierAppleExerciseTime"
    HK_QUANTITY_APPLE_STAND_TIME = "HKQuantityTypeIdentifierAppleStandTime"
    HK_QUANTITY_BASAL_ENERGY_BURNED = "HKQuantityTypeIdentifierBasalEnergyBurned"
    HK_QUANTITY_BLOOD_GLUCOSE = "HKQuantityTypeIdentifierBloodGlucose"
    HK_QUANTITY_BODY_MASS = "HKQuantityTypeIdentifierBodyMass"
    HK_QUANTITY_DISTANCE_CYCLING = "HKQuantityTypeIdentifierDistanceCycling"
    HK_QUANTITY_DISTANCE_WALKING_RUNNING = "HKQuantityTypeIdentifierDistanceWalkingRunning"
    HK_QUANTITY_FLIGHTS_CLIMBED = "HKQuantityTypeIdentifierFlightsClimbed"
    HK_QUANTITY_HEART_RATE = "HKQuantityTypeIdentifierHeartRate"
    HK_QUANTITY_HEART_RATE_RECOVERY_ONE_MINUTE = "HKQuantityTypeIdentifierHeartRateRecoveryOneMinute"
    HK_QUANTITY_HEART_RATE_VARIABILITY_SDNN = "HKQuantityTypeIdentifierHeartRateVariabilitySDNN"
    HK_QUANTITY_HEIGHT = "HKQuantityTypeIdentifierHeight"
    HK_QUANTITY_OXYGEN_SATURATION = "HKQuantityTypeIdentifierOxygenSaturation"
    HK_QUANTITY_RESPIRATORY_RATE = "HKQuantityTypeIdentifierRespiratoryRate"
    HK_QUANTITY_RESTING_HEART_RATE = "HKQuantityTypeIdentifierRestingHeartRate"
    HK_QUANTITY_SIX_MINUTE_WALK_TEST_DISTANCE = "HKQuantityTypeIdentifierSixMinuteWalkTestDistance"
    HK_QUANTITY_STAIR_ASCENT_SPEED = "HKQuantityTypeIdentifierStairAscentSpeed"
    HK_QUANTITY_STAIR_DESCENT_SPEED = "HKQuantityTypeIdentifierStairDescentSpeed"
    HK_QUANTITY_STEP_COUNT = "HKQuantityTypeIdentifierStepCount"
    HK_QUANTITY_VO2_MAX = "HKQuantityTypeIdentifierVO2Max"
    HK_QUANTITY_WALKING_ASYMMETRY_PERCENTAGE = "HKQuantityTypeIdentifierWalkingAsymmetryPercentage"
    HK_QUANTITY_WALKING_DOUBLE_SUPPORT_PERCENTAGE = "HKQuantityTypeIdentifierWalkingDoubleSupportPercentage"
    HK_QUANTITY_WALKING_HEART_RATE_AVERAGE = "HKQuantityTypeIdentifierWalkingHeartRateAverage"
    HK_QUANTITY_WALKING_SPEED = "HKQuantityTypeIdentifierWalkingSpeed"
    HK_QUANTITY_WALKING_STEP_LENGTH = "HKQuantityTypeIdentifierWalkingStepLength"

    # HealthKit category types (e.g., sleep analysis)
    HK_CATEGORY_APPLE_STAND_HOUR = "HKCategoryTypeIdentifierAppleStandHour"
    HK_CATEGORY_LOW_HEART_RATE_EVENT = "HKCategoryTypeIdentifierLowHeartRateEvent"
    HK_CATEGORY_SLEEP_ANALYSIS = "HKCategoryTypeIdentifierSleepAnalysis"

    # HealthKit correlation types (e.g., blood pressure)
    HK_CORRELATION_BLOOD_PRESSURE = "HKCorrelationTypeIdentifierBloodPressure"

    # HealthKit workout types
    HK_WORKOUT = "HKWorkoutTypeIdentifier"

    # HealthKit clinical types (e.g., lab results)
    HK_CLINICAL_ALLERGY_RECORD = "HKClinicalTypeIdentifierAllergyRecord"
    HK_CLINICAL_CLINICAL_NOTE_RECORD = "HKClinicalTypeIdentifierClinicalNoteRecord"
    HK_CLINICAL_CONDITION_RECORD = "HKClinicalTypeIdentifierConditionRecord"
    HK_CLINICAL_IMMUNIZATION_RECORD = "HKClinicalTypeIdentifierImmunizationRecord"
    HK_CLINICAL_LAB_RESULT_RECORD = "HKClinicalTypeIdentifierLabResultRecord"
    HK_CLINICAL_MEDICATION_RECORD = "HKClinicalTypeIdentifierMedicationRecord"
    HK_CLINICAL_PROCEDURE_RECORD = "HKClinicalTypeIdentifierProcedureRecord"
    HK_CLINICAL_VITAL_SIGN_RECORD = "HKClinicalTypeIdentifierVitalSignRecord"

    # HealthKit data types (e.g., heartbeat series)
    HK_DATA_IDENTIFIER_ELECTROCARDIOGRAM = "HKDataTypeIdentifierElectrocardiogram"
    HK_DATA_STATE_OF_MIND = "HKDataTypeStateOfMind"

    # Apple SensorKit types
    SENSORKIT_ALS = "com.apple.SensorKit.als"
    SENSORKIT_AMBIENT_PRESSURE = "com.apple.SensorKit.ambientPressure"
    SENSORKIT_DEVICE_USAGE_REPORT = "com.apple.SensorKit.deviceUsageReport"
    SENSORKIT_HEART_RATE = "com.apple.SensorKit.heart.rate"
    SENSORKIT_MOTION_ACCELEROMETER = "com.apple.SensorKit.motion.accelerometer"
    SENSORKIT_ON_WRIST_STATE = "com.apple.SensorKit.onWristState"
    SENSORKIT_PEDOMETER_DATA = "com.apple.SensorKit.pedometer.data"
    SENSORKIT_PPG = "com.apple.SensorKit.PPG"
    SENSORKIT_VISITS = "com.apple.SensorKit.visits"
    SENSORKIT_WRIST_TEMPERATURE = "com.apple.SensorKit.wristTemperature"

    # MyHeartCounts custom sample types
    MHC_CUSTOM_CUSTOM_SAMPLE_TYPE_BLOOD_LIPID_MEASUREMENT = "MHCCustomSampleTypeBloodLipidMeasurement"
    MHC_CUSTOM_CUSTOM_SAMPLE_TYPE_DIET_MEPA_SCORE = "MHCCustomSampleTypeDietMEPAScore"
    MHC_CUSTOM_CUSTOM_SAMPLE_TYPE_NICOTINE_EXPOSURE = "MHCCustomSampleTypeNicotineExposure"
    MHC_CUSTOM_HEALTH_OBSERVATION_TIMED_WALKING_TEST_RESULT_IDENTIFIER = "MHCHealthObservationTimedWalkingTestResultIdentifier"


def get_observation_type_by_identifier(
    identifier: str,
) -> DiscoveredObservationType | None:
    """Look up an observation type by its raw identifier.

    Args:
        identifier: The raw identifier string
            (e.g., "HKQuantityTypeIdentifierStepCount").

    Returns:
        The matching DiscoveredObservationType, or None if not found.
    """
    for member in DiscoveredObservationType:
        if member.value == identifier:
            return member
    return None
